* Encoding: UTF-8.

DATASET ACTIVATE 数据集1.
GRAPH
  /SCATTERPLOT(MATRIX)=SiO2 Na2O K2O CaO MgO Al2O3 Fe2O3 CuO PbO BaO P2O5 SrO SnO2 SO2
  /MISSING=LISTWISE.

NONPAR CORR
  /VARIABLES=SiO2 Na2O K2O CaO MgO Al2O3 Fe2O3 CuO PbO BaO P2O5 SrO SnO2 SO2
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.
